spring:
    mvc:
          view:
                prefix: /WEB-INF/jsp/
                suffix: .jsp
logging:
    level:
          org.tinywind: TRACE
server:
    error:
          whitelabel:
                enabled: false